# Generated by Django 4.2.1 on 2023-11-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=200, null=True)),
                ('purchaseitems', models.IntegerField()),
                ('solditems', models.IntegerField()),
                ('itempiece', models.IntegerField()),
                ('sales', models.IntegerField()),
                ('purchasedate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
